(() => {
  const c = document.querySelector('#gameCanvas'), x = c.getContext('2d'), $ = s => document.querySelector(s), W = c.width, H = c.height;
  const ui = {coins:$('#coins'),score:$('#score'),speed:$('#speed'),overlay:$('#overlay'),title:$('#overlayTitle'),text:$('#overlayText'),start:$('#startButton'),pause:$('#pauseButton'),boost:$('#boostButton')};
  let g, last, raf; const lanes=[W*.28,W*.5,W*.72], TURBO_COST=5;
  function updateBoostButton(){let locked=g.coins<TURBO_COST;ui.boost.disabled=locked;ui.boost.classList.toggle('cooldown',locked);ui.boost.innerHTML=locked?`⚡ 터보: ${TURBO_COST} 코인 필요 <small>(Space)</small>`:`⚡ 속도 +0.1 <small>(${TURBO_COST} 코인 · Space)</small>`}
  function reset(){g={run:false,pause:false,keys:{},car:W/2,coins:0,score:0,speed:1,road:0,obs:[],spawn:0,coinSpawn:0};ui.coins.textContent=0;ui.score.textContent=0;ui.speed.textContent='1.0x';updateBoostButton()}
  function add(type,lane=Math.floor(Math.random()*3),y=-90){g.obs.push({type,x:lanes[lane],y,phase:Math.random()*7})}
  function addCoinPattern(){const patterns=[[[1,-80],[1,-175],[1,-270],[1,-365],[1,-460]],[[0,-80],[0,-175],[0,-270],[0,-365]],[[2,-80],[2,-175],[2,-270],[2,-365]],[[0,-80],[1,-180],[2,-280],[1,-380],[0,-480]],[[2,-80],[1,-180],[0,-280],[1,-380],[2,-480]],[[0,-100],[1,-100],[2,-100],[0,-230],[1,-230],[2,-230]],[[1,-80],[0,-185],[1,-290],[2,-395],[1,-500]]];patterns[Math.floor(Math.random()*patterns.length)].forEach(([lane,y])=>add('coin',lane,y))}
  function start(){reset();g.run=true;ui.overlay.classList.add('hidden');ui.pause.textContent='Ⅱ';last=performance.now();cancelAnimationFrame(raf);raf=requestAnimationFrame(loop)}
  function end(){g.run=false;ui.title.textContent='충돌했어요!';ui.text.innerHTML=`최종 점수 <b>${Math.floor(g.score)}</b>점 · 코인 <b>${g.coins}</b>개<br>다시 도전해 볼까요?`;ui.start.textContent='다시 시작';ui.overlay.classList.remove('hidden')}
  function boost(){if(!g.run||g.pause||g.coins<TURBO_COST)return;g.coins-=TURBO_COST;g.speed+=.1;updateBoostButton()}
  function update(d){let mv=(g.keys.a||g.keys.l?-1:0)+(g.keys.d||g.keys.r?1:0);g.car=Math.max(110,Math.min(W-110,g.car+mv*380*d));g.road=(g.road+330*g.speed*d)%100;g.score+=10*g.speed*d;g.spawn-=d;g.coinSpawn-=d;if(g.spawn<=0){add('bad');g.spawn=Math.max(.34,1.18-g.speed*.12)+Math.random()*.25}if(g.coinSpawn<=0){addCoinPattern();g.coinSpawn=.85+Math.random()*.2}for(let i=g.obs.length-1;i>=0;i--){let o=g.obs[i];o.y+=300*g.speed*d;let hit=Math.abs(o.x-g.car)<46&&Math.abs(o.y-760)<62;if(hit){if(o.type==='coin'){g.coins++;g.score+=50;g.obs.splice(i,1)}else{return end()}}else if(o.y>H+80)g.obs.splice(i,1)}ui.coins.textContent=g.coins;ui.score.textContent=Math.floor(g.score);ui.speed.textContent=g.speed.toFixed(1)+'x';updateBoostButton()}
  function round(a,b,w,h,r,col){x.fillStyle=col;x.beginPath();x.roundRect(a,b,w,h,r);x.fill()}
  function car(cx,cy,col,small){let s=small?.78:1;x.save();x.translate(cx,cy);x.scale(s,s);x.shadowColor='#0009';x.shadowBlur=10;round(-35,-58,70,116,17,'#101a26');round(-30,-56,60,112,15,col);x.shadowBlur=0;round(-21,-32,42,43,9,'#bcefff');x.fillStyle='#5daeea';x.fillRect(-17,-28,34,10);round(-24,20,48,20,6,'#ffcd37');x.fillStyle='#eaf7ff';x.fillRect(-25,-44,12,7);x.fillRect(13,-44,12,7);x.restore()}
  function coin(o){let p=Math.sin(performance.now()/130+o.phase)*2;x.save();x.translate(o.x,o.y);x.shadowColor='#ffbd22';x.shadowBlur=16;x.fillStyle='#ffd53d';x.beginPath();x.arc(0,0,21+p,0,7);x.fill();x.shadowBlur=0;x.strokeStyle='#a76a00';x.lineWidth=3;x.beginPath();x.arc(0,0,15+p/2,0,7);x.stroke();x.fillStyle='#a76a00';x.font='bold 21px sans-serif';x.textAlign='center';x.textBaseline='middle';x.fillText('C',0,1);x.restore()}
  function draw(){x.clearRect(0,0,W,H);x.fillStyle='#1d5d4d';x.fillRect(0,0,W,H);x.fillStyle='#242d3a';x.beginPath();x.moveTo(90,H);x.lineTo(180,0);x.lineTo(540,0);x.lineTo(630,H);x.closePath();x.fill();x.fillStyle='#c94a40';x.fillRect(90,0,9,H);x.fillRect(621,0,9,H);x.strokeStyle='#f7f1c7';x.lineWidth=10;x.setLineDash([42,58]);x.lineDashOffset=g.road;[W/3.33,W/1.43].forEach(a=>{x.beginPath();x.moveTo(a,0);x.lineTo(a,H);x.stroke()});x.setLineDash([]);g.obs.forEach(o=>o.type==='coin'?coin(o):car(o.x,o.y,'#f25454',true));car(g.car,760,'#36aaff')}
  function loop(t){if(!g.run||g.pause)return;let d=Math.min(.033,(t-last)/1000);last=t;update(d);draw();if(g.run)raf=requestAnimationFrame(loop)}
  addEventListener('keydown',e=>{let k=e.key.toLowerCase();if(['a','d','arrowleft','arrowright',' '].includes(k))e.preventDefault();if(k===' ')boost();if(k==='a')g.keys.a=1;if(k==='d')g.keys.d=1;if(k==='arrowleft')g.keys.l=1;if(k==='arrowright')g.keys.r=1});
  addEventListener('keyup',e=>{let k=e.key.toLowerCase();if(k==='a')g.keys.a=0;if(k==='d')g.keys.d=0;if(k==='arrowleft')g.keys.l=0;if(k==='arrowright')g.keys.r=0});
  c.addEventListener('pointermove',e=>{if(g.run){let r=c.getBoundingClientRect();g.car=Math.max(110,Math.min(W-110,(e.clientX-r.left)/r.width*W))}});
  ui.start.onclick=start;ui.boost.onclick=boost;ui.pause.onclick=()=>{if(!g.run)return;g.pause=!g.pause;ui.pause.textContent=g.pause?'▶':'Ⅱ';if(!g.pause){last=performance.now();raf=requestAnimationFrame(loop)}};
  reset();draw();
})();
